name: oru_phones
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.1
  json_annotation: null
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  carousel_slider: ^5.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.1
  pinput: ^5.0.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/icons/
