// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Ezr_l9eovikswxJp8y_DNYy9t9oEmdI',
    appId: '1:626939571113:web:2b9cd3275a23ea92a2b2b8',
    messagingSenderId: '626939571113',
    projectId: 'oruphones-318f3',
    authDomain: 'oruphones-318f3.firebaseapp.com',
    storageBucket: 'oruphones-318f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRznQglWVDwHDLYmIUYl4TwUpiDzfvZQ',
    appId: '1:626939571113:android:43a80d441bfd0aada2b2b8',
    messagingSenderId: '626939571113',
    projectId: 'oruphones-318f3',
    storageBucket: 'oruphones-318f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-_X0ipz4VcqMZxuYyKCvvT64F0t4JVHI',
    appId: '1:626939571113:ios:4126c314eac28cc5a2b2b8',
    messagingSenderId: '626939571113',
    projectId: 'oruphones-318f3',
    storageBucket: 'oruphones-318f3.firebasestorage.app',
    iosBundleId: 'com.example.oruPhones',
  );
}
